Repository choiseona/commence-project-frontend, pull requests merged in 2024-01, with the labels that each got.

#3 Feat/project setting
  src/App.css
  src/App.tsx
  src/assets/fonts/AppleSDGothicNeoB.ttf
  src/assets/fonts/AppleSDGothicNeoB00.woff
  src/assets/fonts/AppleSDGothicNeoB00.woff2
  src/assets/fonts/AppleSDGothicNeoEB.ttf
  src/assets/fonts/AppleSDGothicNeoEB00.woff
  src/assets/fonts/AppleSDGothicNeoEB00.woff2
  src/assets/fonts/AppleSDGothicNeoH.ttf
  src/assets/fonts/AppleSDGothicNeoH00.woff
  src/assets/fonts/AppleSDGothicNeoH00.woff2
  src/assets/fonts/AppleSDGothicNeoL.ttf
  src/assets/fonts/AppleSDGothicNeoL00.woff
  src/assets/fonts/AppleSDGothicNeoL00.woff2
  src/assets/fonts/AppleSDGothicNeoM.ttf
  src/assets/fonts/AppleSDGothicNeoM00.woff
  src/assets/fonts/AppleSDGothicNeoM00.woff2
  src/assets/fonts/AppleSDGothicNeoR.ttf
  src/assets/fonts/AppleSDGothicNeoR00.woff
  src/assets/fonts/AppleSDGothicNeoR00.woff2
  src/assets/fonts/AppleSDGothicNeoSB.ttf
  src/assets/fonts/AppleSDGothicNeoSB00.woff
  src/assets/fonts/AppleSDGothicNeoSB00.woff2
  src/assets/fonts/AppleSDGothicNeoT.ttf
  src/assets/fonts/AppleSDGothicNeoT00.woff
  src/assets/fonts/AppleSDGothicNeoT00.woff2
  src/assets/fonts/AppleSDGothicNeoUL.ttf
  src/assets/fonts/AppleSDGothicNeoUL00.woff
  src/assets/fonts/AppleSDGothicNeoUL00.woff2
  src/assets/fonts/subset-Pretendard-Regular.ttf
  src/assets/fonts/subset-Pretendard-Regular.woff
  src/assets/fonts/subset-Pretendard-Regular.woff2
  src/assets/react.svg
  src/index.css
  src/pages/MainHome/index.tsx
  yarn.lock
Labels: enhancement

#5 FEAT: 전체 크기 조절 및 layout 컴포넌트 추가 - #4
  src/App.css
  src/App.tsx
  src/assets/svgs/menu.svg
  src/componenet/Layout/index.tsx
  src/componenet/Menu/index.tsx
  src/componenet/Overlay/index.tsx
  src/pages/MainHome/index.tsx
Labels: enhancement

#7 Feature/6 photogallery page UI
  src/App.css
  src/App.tsx
  src/assets/fonts/tvNEnjoystoriesB.ttf
  src/assets/fonts/tvNEnjoystoriesB.woff
  src/assets/fonts/tvNEnjoystoriesB.woff2
  src/assets/fonts/tvNEnjoystoriesL.ttf
  src/assets/fonts/tvNEnjoystoriesL.woff
  src/assets/fonts/tvNEnjoystoriesL.woff2
  src/assets/fonts/tvNEnjoystoriesM.ttf
  src/assets/fonts/tvNEnjoystoriesM.woff
  src/assets/fonts/tvNEnjoystoriesM.woff2
  src/assets/icons/commence-mark.svg
  src/assets/icons/menu-icon.svg
  src/assets/icons/photo-line.svg
  src/assets/svgs/menu.svg
  src/componenet/Common/Layout/index.tsx
  src/componenet/Common/Menu/index.tsx
  src/componenet/Common/Overlay/index.tsx
  src/componenet/Layout/index.tsx
  src/componenet/PhotoGallery/CommenceMark/index.tsx
  src/componenet/PhotoGallery/Comment/index.tsx
  src/componenet/PhotoGallery/PhotoItem/index.tsx
  src/componenet/PhotoGallery/PhotoItems/index.tsx
  src/componenet/PhotoGallery/PhotoLine/index.tsx
  src/componenet/PhotoGallery/ThisYear/index.tsx
  src/data/PhotoGalleryData.ts
  src/index.css
  src/pages/MainHome/index.tsx
  src/pages/PhotoGallery/index.tsx
  tailwind.config.js
Labels: enhancement

#11 Feat/9 Layout component
  src/App.tsx
  src/assets/icons/category-DownArrow.svg
  src/assets/icons/category-UpArrow.svg
  src/assets/icons/commence-smallmark.svg
  src/assets/icons/instagram-smallmark.svg
  src/assets/icons/menu-icon.svg
  src/assets/icons/youtube-smallmark.svg
  src/assets/images/commence-smallmarkPNG.png
  src/assets/images/instagram-smallmarkPNG.png
  src/assets/images/youtue-smallmarkPNG.png
  src/componenet/Common/DeveloperButton/index.tsx
  src/componenet/Common/Footer/index.tsx
  src/componenet/Common/FooterLinks/index.tsx
  src/componenet/Common/FooterText/index.tsx
  src/componenet/Common/FooterTitle/index.tsx
  src/componenet/Common/Header/index.tsx
  src/componenet/Common/Layout/index.tsx
  src/componenet/Common/Menu/index.tsx
  src/componenet/Common/Overlay/index.tsx
  src/pages/About-us/index.tsx
  src/pages/FAQ/index.tsx
  src/pages/How-to-join/index.tsx
  src/pages/Performance-Video/index.tsx
  tailwind.config.js
Labels: enhancement

#13 FIX:Menu 컴포넌트 애니메이션 수정 및 libs/util.ts 폴더/파일 생성
  src/componenet/Common/Header/index.tsx
  src/componenet/Common/Menu/index.tsx
  src/libs/util.ts
Labels: enhancement, invalid

#14 FEAT: font-size 62.5% 설정 - #8
  src/componenet/PhotoGallery/Comment/index.tsx
  src/componenet/PhotoGallery/ThisYear/index.tsx
  src/index.css
Labels: enhancement

#17 FIX: Header,Footer em => %, px => rem 단위 변경
  src/componenet/Common/DeveloperButton/index.tsx
  src/componenet/Common/Footer/index.tsx
  src/componenet/Common/FooterLinks/index.tsx
  src/componenet/Common/FooterText/index.tsx
  src/componenet/Common/FooterTitle/index.tsx
  src/componenet/Common/Header/index.tsx
  src/componenet/Common/Layout/index.tsx
  src/componenet/Common/Menu/index.tsx
Labels: bug, enhancement

#19 FIX: Footer PNG -> SVG
  src/componenet/Common/DeveloperButton/index.tsx
  src/componenet/Common/Footer/index.tsx
  src/componenet/Common/FooterLinks/index.tsx
  src/componenet/Common/FooterTitle/index.tsx
Labels: bug

#20 FIX: 회의때 수정사항들 반영
  src/App.tsx
  src/componenet/Common/DeveloperButton/index.tsx
  src/componenet/Common/FooterLinks/index.tsx
  src/componenet/Common/FooterText/index.tsx
  src/componenet/Common/FooterTitle/index.tsx
  src/componenet/Common/Header/index.tsx
  src/pages/About-us/index.tsx
  src/pages/AboutUs/index.tsx
  src/pages/Performance-Video/index.tsx
  src/pages/PerformanceVideo/index.tsx
Labels: bug

#22 FEAT: PhotoGallery 페이지 수정 사항 적용
  src/componenet/Common/FooterTitle/index.tsx
  src/componenet/PhotoGallery/PhotoItem/index.tsx
  src/data/PhotoGalleryData.ts
Labels: enhancement

#24 Feat/23 bestperformance page UI
  src/assets/icons/play-icon.svg
  src/assets/icons/youtube-redmark.svg
  src/assets/images/Rectangle 12.jpg
  src/assets/images/test.png
  src/componenet/Common/Title/index.tsx
  src/componenet/PerformanceVideo/SubTitle/index.tsx
  src/componenet/PerformanceVideo/VideoItem/index.tsx
  src/componenet/PerformanceVideo/VideoList/index.tsx
  src/componenet/PerformanceVideo/YouTubeButton/index.tsx
  src/data/PerformanceVideoData.ts
  src/pages/HowToJoin/index.tsx
  src/pages/PerformanceVideo/index.tsx
Labels: enhancement

#26 FEAT: HowToJoin 페이지 수정 - #25
  src/pages/HowToJoin/index.tsx
Labels: enhancement

#27 Feat/10 main page UI
  package.json
  src/assets/icons/mainhome-arrow-icon.svg
  src/assets/icons/right-arrow-icon.svg
  src/assets/icons/white-arrow.svg
  src/assets/icons/white-commence-mark.svg
  src/assets/icons/white-instagram-mark.svg
  src/assets/icons/white-youtube-mark.svg
  src/componenet/Common/DeveloperButton/index.tsx
  src/componenet/Common/Menu/index.tsx
  src/componenet/MainHome/CategoryBox/index.tsx
  src/componenet/MainHome/CategoryBoxContainer/index.tsx
  src/componenet/MainHome/JoinUsButton/index.tsx
  src/componenet/MainHome/MainPageSubTitle/index.tsx
  src/componenet/MainHome/MovingBanner/index.tsx
  src/componenet/MainHome/OuterLinkBox/index.tsx
  src/componenet/MainHome/OuterLinksContainer/index.tsx
  src/componenet/MainHome/SlideBanner/index.tsx
  src/componenet/MainHome/SlideBannerText/index.tsx
  src/data/CategoryBoxData.ts
  src/data/OuterLinkBoxData.ts
  src/pages/MainHome/index.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement

#33 FIX: 404 에러 해결 - #32
  vercel.json
Labels: bug
