Repository choiseona/commence-project-frontend, pull requests merged in 2024-02, with the labels that each got.

#36 fix/MainHome 컴포넌트 디자인 수정 및 기타 수정 사항 반영
  src/assets/images/slideimg1.jpg
  src/assets/images/slideimg2.jpg
  src/assets/images/slideimg3.jpg
  src/assets/images/slideimg4.jpg
  src/componenet/AboutUs/AwardsItem/index.tsx
  src/componenet/AboutUs/AwardsItemDot/index.tsx
  src/componenet/Common/Menu/index.tsx
  src/componenet/MainHome/CategoryBox/index.tsx
  src/componenet/MainHome/JoinUsButton/index.tsx
  src/componenet/MainHome/MainPageSubTitle/index.tsx
  src/componenet/MainHome/OuterLinkBox/index.tsx
  src/componenet/MainHome/OuterLinksContainer/index.tsx
  src/componenet/MainHome/SlideBanner/index.tsx
  src/componenet/MainHome/SlideBannerText/index.tsx
  src/data/OuterLinkBoxData.ts
Labels: bug, enhancement

#40 Feat/31 faq page UI
  src/assets/icons/faq-horizon.svg
  src/componenet/AboutUs/AboutUsSubTitle/index.tsx
  src/componenet/AboutUs/AwardsItem/index.tsx
  src/componenet/AboutUs/AwardsItemDot/index.tsx
  src/componenet/AboutUs/IntroduceText/index.tsx
  src/componenet/Common/FooterLinks/index.tsx
  src/componenet/Common/FooterTitle/index.tsx
  src/componenet/Common/Header/index.tsx
  src/componenet/FAQ/FaqContainer/index.tsx
  src/componenet/FAQ/FaqItem/index.tsx
  src/componenet/FAQ/TitleText/index.tsx
  src/data/FaqData.ts
  src/pages/FAQ/index.tsx
Labels: enhancement

#42 Feat/37 photogallery insert photo
  src/assets/icons/photo-line.svg
  src/assets/images/april_1.jpg
  src/assets/images/august-1.jpg
  src/assets/images/december-1.jpg
  src/assets/images/february-1.jpg
  src/assets/images/january-1.jpg
  src/assets/images/january-2.jpg
  src/assets/images/july-1.jpg
  src/assets/images/march-1.jpg
  src/assets/images/march-2.jpg
  src/assets/images/march-3.jpg
  src/assets/images/may-1.jpg
  src/assets/images/may-2.jpg
  src/assets/images/november-1.jpg
  src/assets/images/october-1.jpg
  src/assets/images/september-1.jpg
  src/componenet/PhotoGallery/PhotoItems/index.tsx
  src/data/PhotoGalleryData.ts
Labels: enhancement

#43 FEAT: performance 페이지 css 수정 - #38
  src/componenet/PerformanceVideo/VideoItem/index.tsx
  src/componenet/PerformanceVideo/VideoList/index.tsx
  src/data/PerformanceVideoData.ts
  src/pages/PerformanceVideo/index.tsx
Labels: enhancement

#44 Feat/37 photogallery insert photo
  src/assets/images/KakaoTalk_20240126_202505743_01.jpg
  src/assets/images/april_1.jpg
  src/assets/images/august-1.jpg
  src/assets/images/december-1.jpg
  src/assets/images/february-1.jpg
  src/assets/images/january-1.jpg
  src/assets/images/january-2.jpg
  src/assets/images/july-1.jpg
  src/assets/images/march-1.jpg
  src/assets/images/march-3.jpg
  src/assets/images/may-1.jpg
  src/assets/images/may-2.jpg
  src/assets/images/november-1.jpg
  src/assets/images/september-1.jpg
Labels: enhancement

#45 FEAT: ScrollToTop hook 추가
  src/assets/images/slide1.jpg
  src/assets/images/slide4.jpg
  src/assets/images/slideimg1.jpg
  src/assets/images/slideimg2.jpg
  src/assets/images/slideimg3.jpg
  src/assets/images/slideimg4.jpg
  src/componenet/AboutUs/MainPerformances/index.tsx
  src/componenet/AboutUs/PerformanceBox/index.tsx
  src/componenet/Common/Footer/index.tsx
  src/componenet/Common/Layout/index.tsx
  src/componenet/MainHome/SlideBanner/index.tsx
  src/componenet/MainHome/SlideBannerText/index.tsx
  src/data/MainPerformancesData.ts
  src/libs/ScrollToTop/index.tsx
Labels: bug, enhancement

#47 FIX: 회의 때 말한 수정 사항 반영
  src/App.css
  src/assets/icons/mainhome-arrow-icon.svg
  src/componenet/AboutUs/AboutUsSubTitle/index.tsx
  src/componenet/AboutUs/AwardsItem/index.tsx
  src/componenet/AboutUs/IntroduceText/index.tsx
  src/componenet/AboutUs/PerformanceBox/index.tsx
  src/componenet/Common/FooterLinks/index.tsx
  src/componenet/Common/FooterText/index.tsx
  src/componenet/Common/FooterTitle/index.tsx
  src/componenet/Common/Header/index.tsx
  src/componenet/Common/Menu/index.tsx
  src/componenet/FAQ/FaqContainer/index.tsx
  src/componenet/HowToJoin/ApplyButton/index.tsx
  src/componenet/HowToJoin/AuditionProcedure/index.tsx
  src/componenet/HowToJoin/CommonExplaination/index.tsx
  src/componenet/HowToJoin/PositionExplaination/index.tsx
  src/componenet/MainHome/CategoryBox/index.tsx
  src/componenet/MainHome/MainPageSubTitle/index.tsx
  src/componenet/MainHome/SlideBanner/index.tsx
  src/componenet/MainHome/SlideBannerText/index.tsx
  src/libs/ScrollToTop/index.tsx
  src/pages/FAQ/index.tsx
Labels: enhancement

#49 FEAT: 수정사항 반영 - #48
  src/componenet/Common/Title/index.tsx
  src/componenet/FAQ/TitleText/index.tsx
  src/componenet/HowToJoin/ApplyButton/index.tsx
  src/componenet/HowToJoin/AuditionProcedure/index.tsx
  src/componenet/HowToJoin/AuditionTip/index.tsx
  src/componenet/HowToJoin/Comment/index.tsx
  src/componenet/HowToJoin/CommonExplaination/index.tsx
  src/componenet/HowToJoin/CommonExplainations/index.tsx
  src/componenet/HowToJoin/FirstAuditionExplaination/index.tsx
  src/componenet/HowToJoin/PositionExplainations/index.tsx
  src/componenet/HowToJoin/SecondAuditionExplaination/index.tsx
  src/componenet/HowToJoin/Step/index.tsx
  src/componenet/PhotoGallery/ThisYear/index.tsx
  src/pages/HowToJoin/index.tsx
  src/pages/PerformanceVideo/index.tsx
  src/pages/PhotoGallery/index.tsx
Labels: enhancement

#52 FIX: 최종 수정 사항 반영 - #50
  src/componenet/Common/FooterLinks/index.tsx
  src/componenet/FAQ/FaqItem/index.tsx
  src/componenet/MainHome/SlideBannerText/index.tsx
  src/data/FaqData.ts
  src/data/MainPerformancesData.ts
Labels: enhancement

#53 FEAT: app 아이콘, 명 변경 - #51
  index.html
  public/vite.svg
Labels: enhancement

#55 FEAT: margin 수정 - #54
  src/componenet/HowToJoin/AuditionTip/index.tsx
Labels: enhancement

#56 FEAT: 앱 로고 변경 - #51
  index.html
  public/commence.png
  public/vite.svg
Labels: enhancement

#57 FEAT: SEO 개선 및 README 수정
  README.md
  index.html
  public/robots.txt
  src/componenet/AboutUs/AwardsLine/index.tsx
  src/componenet/AboutUs/HugeCommenceMark/index.tsx
  src/componenet/AboutUs/IntroduceText/index.tsx
  src/componenet/AboutUs/PerformanceBox/index.tsx
  src/componenet/Common/FooterTitle/index.tsx
  src/componenet/MainHome/JoinUsButton/index.tsx
  src/componenet/MainHome/MovingBanner/index.tsx
Labels: documentation, enhancement
